version: '3.3'

services:
  web:
    build:
      context: .
    ports:
      - "80:80" 
    volumes:
      - ./src:/var/www/html
      - ./public:/var/www/html/public
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql